routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');


//Route::get("/agenda","AgendaController@index")->name("agenda.index");
Route::resource('agenda','AgendaController');

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $table = "agendas_teste";


    protected $fillable=['nome',
    'fone_res',
    'dt_nasc',
    'email',
    'facebook',
    'twitter',
    'instagram'
   ];


 protected $dates = [
      'dt_nasc',
      'created_at',
      'updated_at',
 ];

}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Agenda;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB; 

class AgendaController extends Controller
{

    /** 
     *index   - exibe uma lista dos registro da tabela 
     *create  - exibe um form para cadastrar dados
     *store   - recebe os dados do form (create) e envia para o model gravar na tabela (operação de inserção)
     *edit    - exibe o form para alterar dados de determinado registro lido.
     *show    - recebe os dados do form (edit) e envia para  o Model atualizar na tabela(operação de update) -
     *destroy - deleta um determinado registro
     */
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = Agenda::all();
        return view("agenda.index",compact('contatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //  $dt_nasc = $this->formata_data($request->dt_nasc);

         //dd($request);

        DB::table('agendas_teste')->insert([
           'nome'=> $request->nome,
           'fone_res'=> $request->fone_res,
           'dt_nasc' => $request->dt_nasc,
           'email' => $request->email,
           'facebook'=> $request->facebook,
           'twitter' =>  $request->twitter,
           'instagram' => $request->instagram
        ]);
       // Agenda::create($request->all());

        return redirect()->route('agenda.index');
    }


     public function formata_data($data){
       $d = substr($data,6,4) . "-" . substr($data,3,2) . "-" . substr($data,0,2);

       return $d;

     }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function show( $id)
    {
        $agenda = Agenda::find($id);

        return view('agenda.show',compact('agenda'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $agenda = Agenda::find($id);
        return view('agenda.edit',compact('agenda'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //$dt_nasc = $this->formata_data($request->dt_nasc);


       // dd($request,$dt_nasc);
        DB::table('agendas_teste')
        ->where('id',$id)
        ->update([
            'nome'=> $request->nome,
            'fone_res'=> $request->fone_res,
            'dt_nasc' => $request->dt_nasc,
            'email' => $request->email,
            'facebook'=> $request->facebook,
            'twitter' =>  $request->twitter,
            'instagram' => $request->instagram
         ]);

         return redirect()->route('agenda.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agenda $agenda)
    {
        //
    }
}

resources/views/agenda/create.blade.php
@extends('adminlte::page')

@section('title', 'Agendal6')

@section('content_header')
<h1> Criação de um Contato</h1>
@stop

<!-- div.panel.panel-default -->
@section('content')
  <form action="{{ route('agenda.store') }} " method="POST">
   {{ csrf_field() }} 
    <div class="panel panel-default">

      <div class="panel-heading">
         cadastro de novos contatos
      </div>


     <div class="panel-body">
         <div class="form-group">
          <label for="nome" >Nome do contato:</label>
          <input type="text" id="nome" name="nome" class="form-control">
    </div>
     

  
     <div class="form-group">
          <label for="fone_res" >Telefone:</label>
          <input type="text" id="fone_res" name="fone_res" class="form-control">
    </div>
     

    
   
     <div class="form-group">
          <label for="dt_nasc" >Data:</label>
          <input type="date" id="dt_nasc" name="dt_nasc" class="form-control">
          
     </div>



     <div class="form-group">
          <label for="email" >email:</label>
          <input type="text" id="email" name="email" class="form-control">
          
     </div>



     <div class="form-group">
          <label for="facebook">facebook:</label>
          <input type="text" id="facebook" name="facebook" class="form-control">
          
     </div>


     <div class="form-group">
          <label for="twitter" nome do contato>twitter:</label>
          <input type="text" id="twitter" name="twitter" class="form-control">
          
     </div>

     
     <div class="form-group">
          <label for="instagram" nome do contato>Instagram:</label>
          <input type="text" id="instagram" name="instagram" class="form-control">
          
     </div>



 </div>


    <div class="panel-footer">
      <a href="{{ route('agenda.index') }}" class="btn btn-default">
        <i class="fas fa-reply"></i> voltar
      </a>

      <button  type="submit" class="btn btn-success">
         <i class="fas fa-save"></i>Gravar
       </button>         
    </div>



</div>
  
  </form>
@stop


@section('css')

@stop


@section('js')

@stop

resources/views/agenda/edit.blade.php
@extends('adminlte::page')

@section('title', 'Agendal6')

@section('content_header')
<h1> Edição dos dados do contato</h1>
@stop

<!-- div.panel.panel-default -->
@section('content')
  <form action="{{ route('agenda.update',$agenda->id) }} " method="POST">
   {{ csrf_field() }}  
   <input type="hidden" name="_method" value="PUT">
    <div class="panel panel-default">

      <div class="panel-heading">
         Alteraçoes do dados do contato
      </div>


     <div class="panel-body">
         <div class="form-group">
          <label for="nome" >Nome do contato:</label>
          <input type="text" id="nome" name="nome" class="form-control" value="{{$agenda->nome}}">
    </div>
     

  
     <div class="form-group">
          <label for="fone_res" >Telefone:</label>
          <input type="text" id="fone_res" name="fone_res" class="form-control" value="{{$agenda->fone_res}}">
    </div>
     

    
   
     <div class="form-group">
          <label for="dt_nasc" >Data:</label>
          <input type="date" id="dt_nasc" name="dt_nasc" class="form-control" value="{{$agenda->dt_nasc->format('d/m/Y')}}">
          
     </div>



     <div class="form-group">
          <label for="email" >email:</label>
          <input type="text" id="email" name="email" class="form-control" value="{{$agenda->email}}">
          
     </div>



     <div class="form-group">
          <label for="facebook">facebook:</label>
          <input type="text" id="facebook" name="facebook" class="form-control" value="{{$agenda->facebook}}">
          
     </div>


     <div class="form-group">
          <label for="twitter" nome do contato>twitter:</label>
          <input type="text" id="twitter" name="twitter" class="form-control" value="{{$agenda->twitter}}">
          
     </div>

     
     <div class="form-group">
          <label for="instagram" nome do contato>Instagram:</label>
          <input type="text" id="instagram" name="instagram" class="form-control" value="{{$agenda->instagram}}">
          
     </div>



 </div>


    <div class="panel-footer">
      <a href="{{ route('agenda.index') }}" class="btn btn-default">
        <i class="fas fa-reply"></i> voltar
      </a>

      <button  type="submit" class="btn btn-success">
         <i class="fas fa-save"></i>Gravar
       </button>         
    </div>



</div>
  
  </form>
@stop


@section('css')

@stop


@section('js')

@stop

resources/views/agenda/index.blade.php
@extends('adminlte::page')

@section('title', 'Agenda')

@section('content_header')
<h1><i class="fa fa-book" aria-hidden="true"></i> Lista de Agendas</h1>
@stop

@section('content')
  <div class="panel panel-default">
     <div class="panel-heading clearfix"> 
       Relação dos contatos da agenda
       <div class="pull-right">
       <a href="{{ route('agenda.index')}}" class="btn btn-primary btn-sm"><i class="fas fa-fax fa-sync-alt"></i> Atualizar a Tela</a> 
       <a href="{{ route('agenda.create')}}" class="btn btn-success btn-sm"><i class="fas fa-fax fa-plus"></i> Adicionar novo contato</a> 
      </div>
  
     </div>


     <div class="panel-body">
          <table id="tabela" class="table table-striped table-bordered table-hover">

          <thead>
               <tr>
                   <th>ID</th>
                   <th>Nome</th>
                   <th>Celular</th>
                   <th>Email</th>
                   <th>facebook</th>
                   
               </tr>
          </thead>


          <tbody>
              @foreach($contatos as $contato)
              <tr>
                <td>{{$contato->id}}</td>
                <td>{{$contato->nome}}</td>
                <td>{{$contato->fone_res}}</td>
                <td>{{$contato->email}}</td>
                <td>{{$contato->facebook}}</td>
                <td>

              
                <a href="{{ route('agenda.show',  $contato->id) }}" class="btn btn-primary btn-xs">
                  <i class="fas fa-fx fa-eye"></i>
                </a>

                <a href="{{ route('agenda.edit',  $contato->id) }}" class="btn btn-warning btn-xs">
                  <i class="fas fa-fx fa-edit"></i>
                </a>

                </td>
             </tr>
             @endforeach
          </tbody>  
            

          </table>
     </div>




  </div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script> 
$(document).ready( function () {
    $('#tabela').DataTable();
} );
</script>
@stop

resources/views/agenda/pagina.blade.php
Ola

resources/views/agenda/show.blade.php
@extends('adminlte::page')

@section('title', 'Agendaa')

@section('content_header')
<h1>Exibição dos dados do contato</h1>
@stop

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">
    Exibe os dados do contato
  </div>

    <div class="panel-body">
      <table class= "table table-bordered table-hover table-striped">
         <tbody>
              <tr>
                <td class="col-md-2">ID</td>
                <td class="col-md-10">{{$agenda->id}}</td>
              </tr>
          
              <tr>
                <td class="col-md-2">Nome</td>
                <td class="col-md-10">{{$agenda->nome}}</td>

              </tr>

              <tr>
                <td class="col-md-2">Telefone</td>
                <td class="col-md-10">{{$agenda->fone_res}}</td>

              </tr>

              <tr>
                <td class="col-md-2">email</td>
                <td class="col-md-10">{{$agenda->email}}</td>

              </tr>

              <tr>
                <td class="col-md-2">Facebook</td>
                <td class="col-md-10">{{$agenda->facebook}}</td>

              </tr>

              <tr>
                <td class="col-md-2">twitter</td>
                <td class="col-md-10">{{$agenda->twitter}}</td>

              </tr>

              <tr>
                <td class="col-md-2">Instagram</td>
                <td class="col-md-10">{{$agenda->instagram}}</td>

              </tr>

              <tr>
                <td class="col-md-2">Data</td>
                <td class="col-md-10">{{date('d/m/Y',strtotime($agenda->dt_nasc))}}</td>
            
              </tr>

           
                

         </tbody>
      </table>
    </div>



    <div class="panel-footer">
      <a href="{{ route('agenda.index') }}" class="btn btn-default">
        <i class="fas fa-reply"></i> voltar
      </a>

    </div>

</div>
@stop



@section('css')

@stop



@section('js')

@stop